version: '3.8'

services:
  m347-kn04b-db:
    image: fabiano4392/m347:kn02b-db
    container_name: m347-kn04b-db
    networks:
      m347-net:
        ipv4_address: 172.20.5.3

  m347-kn04b-web:
    image: fabiano4392/m347:kn02b-web
    container_name: m347-kn04b-web
    networks:
      m347-net:
        ipv4_address: 172.20.5.4
    ports:
      - "8086:80"

networks:
  m347-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          ip_range: 172.20.5.0/24
          gateway: 172.20.5.254
