version: "3.9"

services:
  web1:
    image: nginx
    container_name: web1
    volumes:
      - type: bind
        source: ./bind
        target: /bind
      - type: volume
        source: namedvol
        target: /named
      - type: tmpfs
        target: /tmpfs

  web2:
    image: nginx
    container_name: web2
    volumes:
      - namedvol:/named

volumes:
  namedvol:
